server:
  port: 8080

spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.69.65.203:3306/myshop_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  redis:
    host: 52.69.65.203
    port: 6379
    password:
    database: 0
    timeout: 3000ms
  rabbitmq:
    host: 52.69.65.203
    port: 5672
    username: guest
    password: guest
    virtual-host: /

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml  # 配置xml文件的位置

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

logging:
  level:
    root: INFO
    top.mhxi: DEBUG
    org.springframework.web: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/myshop-order-service.log

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 52.69.65.203
    non-secure-port: 8006
  client:
    service-url:
      defaultZone: http://52.69.65.203:8761/eureka/