server:
  port: 8080

spring:
  application:
    name: file
  redis:
    host: 52.69.65.203
    port: 6379
    password:
    database: 0
    timeout: 3000ms

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

logging:
  level:
    root: INFO
    top.mhxi: DEBUG
    org.springframework.web: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/myshop-file-service.log

aws:
  s3:
    bucket: top-mhxi-myshop-product-images
    region: ap-northeast-1
    accessKey: ${AWS_S3_ACCESSKEY}
    secretKey: ${AWS_S3_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://52.69.65.203:8761/eureka/