server:
  port: 8080

spring:
  application:
    name: cart

  redis:
    host: 52.69.65.203
    port: 6379
    password:
    database: 0
    timeout: 3000ms


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

logging:
  level:
    root: INFO
    top.mhxi: DEBUG
    org.springframework.web: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/myshop-cart-service.log

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 52.69.65.203
    non-secure-port: 8005
  client:
    service-url:
      defaultZone: http://52.69.65.203:8761/eureka/